version: '3.8'

services:
  college_db:
    image: mongo:latest
    ports:
      - "27017:27017"
    restart: always
    volumes:
      - mongo_data:/data/db

  backend1:
    build: .
    command: python backend_server.py
    environment:
      - PORT=5001
      - MONGO_HOST=college_db
    depends_on:
      - college_db

  central:
    build: .
    command: python central_server.py
    ports:
      - "5500:5000"
    environment:
      - BACKEND_1=http://backend1:5001
    depends_on:
      - backend1

volumes:
  mongo_data:
